
function PLUGIN:AddOverwatchVoice(clip, key, value, soldier)
    local soldier = soldier or true
    local vtype = "OTA"
    if (soldier) then
        Schema.voices.Add(vtype, key, value, "npc/combine_soldier/vo/" .. clip .. ".wav")
    else
        Schema.voices.Add(vtype, key, value, "npc/metropolice/vo/" .. clip .. ".wav")
    end
end

function PLUGIN:AddCPVoice(clip, key, value, soldier)
    local soldier = soldier or false
    local vtype = "CP"
    if (soldier) then
        Schema.voices.Add(vtype, key, value, "npc/combine_soldier/vo/" .. clip .. ".wav")
    else
        Schema.voices.Add(vtype, key, value, "npc/metropolice/vo/" .. clip .. ".wav")
    end
end


function PLUGIN:AddDispatchVoice(clip, key, value, city) -- npc/overwatch/radiovoice/404zone.wav npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav
    local city = city or false
    local vtype = "Dispatch"
    if (city) then
        Schema.voices.Add(vtype, key, value, "npc/overwatch/cityvoice/" .. clip .. ".wav")
    else
        Schema.voices.Add(vtype, key, value, "npc/overwatch/radiovoice/" .. clip .. ".wav")
    end
end


function PLUGIN:AddBadCopLine(clip, key, value, blooper)
    local blooper = blooper or false
    local vtype = "CP"
    if (blooper) then
        Schema.voices.Add(vtype, key, value, "badcop/bloopers/" .. clip .. ".wav")
    else
        Schema.voices.Add(vtype, key, value, "badcop/" .. clip .. ".wav")
    end
end

-- SHARED LINES
Schema.voices.Add("CP", "AFFIRMATIVE2", "Affirmative.", "npc/combine_soldier/vo/affirmative2.wav")
Schema.voices.Add("CP", "AFFIRMATIVE3", "Affirmative.", "npc/combine_soldier/vo/affirmative.wav")
Schema.voices.Add("CP", "NO CONTACT", "No contact.", "npc/metropolice/vo/nocontact.wav")
Schema.voices.Add("OTA", "AFFIRMATIVE2", "Affirmative.", "npc/combine_soldier/vo/affirmative2.wav")
Schema.voices.Add("OTA", "AFFIRMATIVE3", "Affirmative.", "npc/combine_soldier/vo/affirmative.wav")
Schema.voices.Add("OTA", "NO CONTACT", "No contact.", "npc/metropolice/vo/nocontact.wav")

Schema.voices.Add("OTA", "AFFIRMATIVE", "Affirmative.", "npc/metropolice/vo/affirmative.wav")
Schema.voices.Add("OTA", "ALL UNITS MOVE", "All units, move in!", "npc/metropolice/vo/allunitsmovein.wav")
Schema.voices.Add("OTA", "AMPUTATE", "Amputate.", "npc/metropolice/vo/amputate.wav")
Schema.voices.Add("OTA", "ANTICITIZEN", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav")
Schema.voices.Add("OTA", "APEX", "Apex.", "npc/combine_soldier/vo/apex.wav")
Schema.voices.Add("OTA", "APPLY", "Apply.", "npc/metropolice/vo/apply.wav")
Schema.voices.Add("OTA", "AT LOCATION REPORT", "Protection-teams at location, report in.", "npc/metropolice/vo/ptatlocationreport.wav")
Schema.voices.Add("OTA", "BLOCK", "Block!", "npc/metropolice/vo/block.wav")
Schema.voices.Add("OTA", "BOOMER", "Boomer.", "npc/combine_soldier/vo/boomer.wav")
Schema.voices.Add("OTA", "CANAL", "Canal.", "npc/metropolice/vo/canal.wav")
Schema.voices.Add("OTA", "CANALBLOCK", "Canalblock!", "npc/metropolice/vo/canalblock.wav")
Schema.voices.Add("OTA", "CAUTERIZE", "Cauterize.", "npc/metropolice/vo/cauterize.wav")
Schema.voices.Add("OTA", "CHECK MISCOUNT", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav")
Schema.voices.Add("OTA", "CITIZEN", "Citizen.", "npc/metropolice/vo/citizen.wav")
Schema.voices.Add("OTA", "CLEAR CODE 100", "Clear and code one-hundred.", "npc/metropolice/vo/clearandcode100.wav")
Schema.voices.Add("OTA", "CODE 100", "Code one-hundred.", "npc/metropolice/vo/code100.wav")
Schema.voices.Add("OTA", "CODE 2", "All units, code two!", "npc/metropolice/vo/allunitscode2.wav")
Schema.voices.Add("OTA", "CODE 7", "Code seven.", "npc/metropolice/vo/code7.wav")
Schema.voices.Add("OTA", "CONDEMNED", "Condemned zone!", "npc/metropolice/vo/condemnedzone.wav")
Schema.voices.Add("OTA", "CONTROL 100", "Control is one-hundred percent this location, no sign of that 647-E.", "npc/metropolice/vo/control100percent.wav")
Schema.voices.Add("OTA", "CONTROLSECTION", "Control-section!", "npc/metropolice/vo/controlsection.wav")
Schema.voices.Add("OTA", "CONVERGING", "Converging.", "npc/metropolice/vo/converging.wav")
Schema.voices.Add("OTA", "DAGGER", "Dagger.", "npc/combine_soldier/vo/dagger.wav")
Schema.voices.Add("OTA", "DASH", "Dash.", "npc/combine_soldier/vo/dash.wav")
Schema.voices.Add("OTA", "DESIGNATE SUSPECT", "Designate suspect as...", "npc/metropolice/vo/designatesuspectas.wav")
Schema.voices.Add("OTA", "DESTROY COVER", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav")
Schema.voices.Add("OTA", "DISMOUNTING HARDPOINT", "Dismounting hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav")
Schema.voices.Add("OTA", "DISTRIBUTION BLOCK", "Distribution block.", "npc/metropolice/vo/distributionblock.wav")
Schema.voices.Add("OTA", "DOCUMENT", "Document.", "npc/metropolice/vo/document.wav")
Schema.voices.Add("OTA", "ECHO", "Echo.", "npc/combine_soldier/vo/echo.wav")
Schema.voices.Add("OTA", "GHOST", "Ghost.", "npc/combine_soldier/vo/ghost.wav")
Schema.voices.Add("OTA", "GRID", "Grid.", "npc/combine_soldier/vo/grid.wav")
Schema.voices.Add("OTA", "HAMMER", "Hammer.", "npc/combine_soldier/vo/hammer.wav")
Schema.voices.Add("OTA", "HELIX", "Helix.", "npc/combine_soldier/vo/helix.wav")
Schema.voices.Add("OTA", "HUNTER", "Hunter.", "npc/combine_soldier/vo/hunter.wav")
Schema.voices.Add("OTA", "HURRICANE", "Hurricane.", "npc/combine_soldier/vo/hurricane.wav")
Schema.voices.Add("OTA", "ICE", "Ice.", "npc/combine_soldier/vo/ice.wav")
Schema.voices.Add("OTA", "INBOUND", "Inbound.", "npc/combine_soldier/vo/inbound.wav")
Schema.voices.Add("OTA", "INFECTED", "Infected.", "npc/combine_soldier/vo/infected.wav")
Schema.voices.Add("OTA", "INFECTION", "Infection!", "npc/metropolice/vo/infection.wav")
Schema.voices.Add("OTA", "INFESTED", "Infested zone.", "npc/metropolice/vo/infestedzone.wav")
Schema.voices.Add("OTA", "INJECT", "Inject!", "npc/metropolice/vo/inject.wav")
Schema.voices.Add("OTA", "INOCULATE", "Inoculate.", "npc/metropolice/vo/innoculate.wav")
Schema.voices.Add("OTA", "INTERCEDE", "Intercede!", "npc/metropolice/vo/intercede.wav")
Schema.voices.Add("OTA", "INTERLOCK", "Interlock!", "npc/metropolice/vo/interlock.wav")
Schema.voices.Add("OTA", "INVESTIGATE", "Investigate.", "npc/metropolice/vo/investigate.wav")
Schema.voices.Add("OTA", "ION", "Ion.", "npc/combine_soldier/vo/ion.wav")
Schema.voices.Add("OTA", "IS 10-8", "Unit is 10-8, standing by.", "npc/metropolice/vo/unitis10-8standingby.wav")
Schema.voices.Add("OTA", "IS DOWN", "Is down!", "npc/metropolice/vo/isdown.wav")
Schema.voices.Add("OTA", "IS INBOUND", "Unit is inbound.", "npc/combine_soldier/vo/unitisinbound.wav")
Schema.voices.Add("OTA", "ISOLATE", "Isolate!", "npc/metropolice/vo/isolate.wav")
Schema.voices.Add("OTA", "JET", "Jet.", "npc/combine_soldier/vo/jet.wav")
Schema.voices.Add("OTA", "JUDGE", "Judge.", "npc/combine_soldier/vo/judge.wav")
Schema.voices.Add("OTA", "JURISDICTION", "Stabilization-jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav")
Schema.voices.Add("OTA", "JURY", "Jury!", "npc/metropolice/vo/jury.wav")
Schema.voices.Add("OTA", "KILO", "Kilo.", "npc/combine_soldier/vo/kilo.wav")
Schema.voices.Add("OTA", "KING", "King!", "npc/metropolice/vo/king.wav")
Schema.voices.Add("OTA", "LEADER", "Leader.", "npc/combine_soldier/vo/leader.wav")
Schema.voices.Add("OTA", "LINE", "Line!", "npc/metropolice/vo/line.wav")
Schema.voices.Add("OTA", "LOCATION", "Location?", "npc/metropolice/vo/location.wav")
Schema.voices.Add("OTA", "LOCK", "Lock!", "npc/metropolice/vo/lock.wav")
Schema.voices.Add("OTA", "MOVE IN", "Move in!", "npc/combine_soldier/vo/movein.wav")
Schema.voices.Add("OTA", "MOVE", "Move!", "npc/metropolice/vo/move.wav")
Schema.voices.Add("OTA", "NOMAD", "Nomad.", "npc/combine_soldier/vo/nomad.wav")
Schema.voices.Add("OTA", "NONPATROL", "Non-patrol region.", "npc/metropolice/vo/nonpatrolregion.wav")
Schema.voices.Add("OTA", "NOVA", "Nova.", "npc/combine_soldier/vo/nova.wav")
Schema.voices.Add("OTA", "OVERWATCH", "Overwatch.", "npc/combine_soldier/vo/overwatch.wav")
Schema.voices.Add("OTA", "PATROL", "Patrol!", "npc/metropolice/vo/patrol.wav")
Schema.voices.Add("OTA", "PAYBACK", "Payback.", "npc/combine_soldier/vo/payback.wav")
Schema.voices.Add("OTA", "PHANTOM", "Phantom.", "npc/combine_soldier/vo/phantom.wav")
Schema.voices.Add("OTA", "PROSECUTE", "Prosecute!", "npc/metropolice/vo/prosecute.wav")
Schema.voices.Add("OTA", "PROSECUTING", "Prosecuting.", "npc/combine_soldier/vo/prosecuting.wav")
Schema.voices.Add("OTA", "QUICK", "Quick!", "npc/metropolice/vo/quick.wav")
Schema.voices.Add("OTA", "QUICKSAND", "Quicksand.", "npc/combine_soldier/vo/quicksand.wav")
Schema.voices.Add("OTA", "RANGE", "Range.", "npc/combine_soldier/vo/range.wav")
Schema.voices.Add("OTA", "RANGER", "Ranger.", "npc/combine_soldier/vo/ranger.wav")
Schema.voices.Add("OTA", "RAZOR", "Razor.", "npc/combine_soldier/vo/razor.wav")
Schema.voices.Add("OTA", "READY CHARGES", "Ready charges!", "npc/combine_soldier/vo/readycharges.wav")
Schema.voices.Add("OTA", "READY PROSECUTE", "Ready to prosecute!", "npc/metropolice/vo/readytoprosecute.wav")
Schema.voices.Add("OTA", "READY WEAPONS", "Ready weapons!", "npc/combine_soldier/vo/readyweapons.wav")
Schema.voices.Add("OTA", "REAPER", "Reaper.", "npc/combine_soldier/vo/reaper.wav")
Schema.voices.Add("OTA", "REPORT CLEAR", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav")
Schema.voices.Add("OTA", "REPORT STATUS", "Local CP-teams, report status.", "npc/metropolice/vo/localcptreportstatus.wav")
Schema.voices.Add("OTA", "REPURPOSED", "Repurposed area.", "npc/metropolice/vo/repurposedarea.wav")
Schema.voices.Add("OTA", "RESIDENTIAL BLOCK", "Residential block.", "npc/metropolice/vo/residentialblock.wav")
Schema.voices.Add("OTA", "RESPONDING", "Responding.", "npc/metropolice/vo/responding2.wav")
Schema.voices.Add("OTA", "RESTRICT", "Restrict!", "npc/metropolice/vo/restrict.wav")
Schema.voices.Add("OTA", "RESTRICTED", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav")
Schema.voices.Add("OTA", "RESTRICTION ZONE", "Terminal restriction-zone!", "npc/metropolice/vo/terminalrestrictionzone.wav")
Schema.voices.Add("OTA", "RIPCORD", "Ripcord", "npc/combine_soldier/vo/ripcord.wav")
Schema.voices.Add("OTA", "ROLLER", "Roller!", "npc/metropolice/vo/roller.wav")
Schema.voices.Add("OTA", "SAVAGE", "Savage.", "npc/combine_soldier/vo/savage.wav")
Schema.voices.Add("OTA", "SCAR", "Scar.", "npc/combine_soldier/vo/scar.wav")
Schema.voices.Add("OTA", "SEARCH", "Search!", "npc/metropolice/vo/search.wav")
Schema.voices.Add("OTA", "SECTOR NOT SECURE", "Sector is not secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
Schema.voices.Add("OTA", "SECTOR IS NOT SECURE", "Sector is not secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
Schema.voices.Add("OTA", "SECTOR NOT STERILE", "Confirmed- sector not sterile.", "npc/combine_soldier/vo/confirmsectornotsterile.wav")
Schema.voices.Add("OTA", "SECURE", "Secure.", "npc/combine_soldier/vo/secure.wav")
Schema.voices.Add("OTA", "SHADOW", "Shadow.", "npc/combine_soldier/vo/shadow.wav")
Schema.voices.Add("OTA", "SHARPZONE", "Sharpzone.", "npc/combine_soldier/vo/sharpzone.wav")
Schema.voices.Add("OTA", "SHIT", "Shit!", "npc/metropolice/vo/shit.wav")
Schema.voices.Add("OTA", "SLAM", "Slam.", "npc/combine_soldier/vo/slam.wav")
Schema.voices.Add("OTA", "SLASH", "Slash.", "npc/combine_soldier/vo/slash.wav")
Schema.voices.Add("OTA", "SOCIOCIDE", "Sociocide.", "npc/metropolice/vo/sociocide.wav")
Schema.voices.Add("OTA", "SOCIOSTABLE", "We are socio-stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav")
Schema.voices.Add("OTA", "SPEAR", "Spear.", "npc/combine_soldier/vo/spear.wav")
Schema.voices.Add("OTA", "STAB", "Stab.", "npc/combine_soldier/vo/stab.wav")
Schema.voices.Add("OTA", "STANDING BY", "Standing by.", "npc/combine_soldier/vo/standingby.wav")
Schema.voices.Add("OTA", "STAR", "Star.", "npc/combine_soldier/vo/star.wav")
Schema.voices.Add("OTA", "STATIONBLOCK", "Stationblock.", "npc/metropolice/vo/stationblock.wav")
Schema.voices.Add("OTA", "STAY ALERT", "Stay alert.", "npc/combine_soldier/vo/stayalert.wav")
Schema.voices.Add("OTA", "STERILIZE", "Sterilize!", "npc/metropolice/vo/sterilize.wav")
Schema.voices.Add("OTA", "STINGER", "Stinger.", "npc/combine_soldier/vo/stinger.wav")
Schema.voices.Add("OTA", "STORM", "Storm.", "npc/combine_soldier/vo/storm.wav")
Schema.voices.Add("OTA", "STRIKER", "Striker.", "npc/combine_soldier/vo/striker.wav")
Schema.voices.Add("OTA", "SUBJECT 505", "Subject is 505!", "npc/metropolice/vo/subjectis505.wav")
Schema.voices.Add("OTA", "SUBJECT HIGH SPEED", "All units, be advised, subject is now high-speed!", "npc/metropolice/vo/subjectisnowhighspeed.wav")
Schema.voices.Add("OTA", "SUBJECT", "Subject!", "npc/metropolice/vo/subject.wav")
Schema.voices.Add("OTA", "SUNDOWN", "Sundown.", "npc/combine_soldier/vo/sundown.wav")
Schema.voices.Add("OTA", "SUSPECT AS", "Designate suspect as...", "npc/metropolice/vo/designatesuspectas.wav")
Schema.voices.Add("OTA", "SUSPEND", "Suspend!", "npc/metropolice/vo/suspend.wav")
Schema.voices.Add("OTA", "SWEEPER", "Sweeper.", "npc/combine_soldier/vo/sweeper.wav")
Schema.voices.Add("OTA", "SWEEPING IN", "Sweeping in!", "npc/combine_soldier/vo/sweepingin.wav")
Schema.voices.Add("OTA", "SWEEPING SUSPECT", "Sweeping for suspect!", "npc/metropolice/vo/sweepingforsuspect.wav")
Schema.voices.Add("OTA", "SWIFT", "Swift.", "npc/combine_soldier/vo/swift.wav")
Schema.voices.Add("OTA", "SWORD", "Sword.", "npc/combine_soldier/vo/sword.wav")
Schema.voices.Add("OTA", "TAG 10-91D", "Tag 10-91d!", "npc/metropolice/vo/tag10-91d.wav")
Schema.voices.Add("OTA", "TAG BUG", "Tag one bug!", "npc/metropolice/vo/tagonebug.wav")
Schema.voices.Add("OTA", "TAG NECROTIC", "Tag one necrotic!", "npc/metropolice/vo/tagonenecrotic.wav")
Schema.voices.Add("OTA", "TAG PARASITIC", "Tag one parasitic!", "npc/metropolice/vo/tagoneparasitic.wav")
Schema.voices.Add("OTA", "TAP", "Tap!", "npc/metropolice/vo/tap.wav")
Schema.voices.Add("OTA", "TARGET", "Target.", "npc/combine_soldier/vo/target.wav")
Schema.voices.Add("OTA", "TRACKER", "Tracker.", "npc/combine_soldier/vo/tracker.wav")
Schema.voices.Add("OTA", "TRANSITBLOCK", "Transit-block.", "npc/metropolice/vo/transitblock.wav")
Schema.voices.Add("OTA", "UNIFORM", "Uniform.", "npc/combine_soldier/vo/uniform.wav")
Schema.voices.Add("OTA", "UNION", "Union!", "npc/metropolice/vo/union.wav")
Schema.voices.Add("OTA", "VAMP", "Vamp.", "npc/combine_soldier/vo/vamp.wav")
Schema.voices.Add("OTA", "VICTOR", "Victor!", "npc/metropolice/vo/victor.wav")
Schema.voices.Add("OTA", "VISCON", "Viscon.", "npc/combine_soldier/vo/viscon.wav")
Schema.voices.Add("OTA", "VISUAL EXOGEN", "Visual on exogen.", "npc/combine_soldier/vo/visualonexogens.wav")
Schema.voices.Add("OTA", "WASTERIVER", "Wasteriver.", "npc/metropolice/vo/wasteriver.wav")
Schema.voices.Add("OTA", "WINDER", "Winder.", "npc/combine_soldier/vo/winder.wav")
Schema.voices.Add("OTA", "WORKFORCE", "Workforce intake.", "npc/metropolice/vo/workforceintake.wav")
Schema.voices.Add("OTA", "WRAP IT UP", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav")
Schema.voices.Add("OTA", "XRAY", "XRay!", "npc/metropolice/vo/xray.wav")
Schema.voices.Add("OTA", "YELLOW", "Yellow!", "npc/metropolice/vo/yellow.wav")
Schema.voices.Add("OTA", "ZONE", "Zone!", "npc/metropolice/vo/zone.wav")
Schema.voices.Add("OTA", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav")
Schema.voices.Add("OTA", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav")

PLUGIN:AddCPVoice("zero", "0", "Zero")
PLUGIN:AddCPVoice("one", "1", "One")
PLUGIN:AddCPVoice("two", "2", "Two")
PLUGIN:AddCPVoice("three", "3", "Three")
PLUGIN:AddCPVoice("four", "4", "Four")
PLUGIN:AddCPVoice("five", "5", "Five")
PLUGIN:AddCPVoice("six", "6", "Six")
PLUGIN:AddCPVoice("seven", "7", "Seven")
PLUGIN:AddCPVoice("eight", "8", "Eight")
PLUGIN:AddCPVoice("nine", "9", "Nine")
PLUGIN:AddCPVoice("ten", "10", "Ten")
PLUGIN:AddCPVoice("eleven", "11", "Eleven")
PLUGIN:AddCPVoice("twelve", "12", "Twelve")
PLUGIN:AddCPVoice("thirteen", "13", "Thirteen")
PLUGIN:AddCPVoice("fourteen", "14", "Fourteen")
PLUGIN:AddCPVoice("fifteen", "15", "Fifteen")
PLUGIN:AddCPVoice("sixteen", "16", "Sixteen")
PLUGIN:AddCPVoice("seventeen", "17", "Seventeen")
PLUGIN:AddCPVoice("eighteen", "18", "Eighteen")
PLUGIN:AddCPVoice("nineteen", "19", "Nineteen")
PLUGIN:AddCPVoice("twenty", "20", "Twenty")
PLUGIN:AddCPVoice("thirty", "30", "Thirty")
PLUGIN:AddCPVoice("fourty", "40", "Fourty")
PLUGIN:AddCPVoice("fifty", "50", "Fifty")
PLUGIN:AddCPVoice("sixty", "60", "Sixty")
PLUGIN:AddCPVoice("seventy", "70", "Seventy")
PLUGIN:AddCPVoice("eighty", "80", "Eighty")
PLUGIN:AddCPVoice("ninety", "90", "Ninety")
PLUGIN:AddCPVoice("onehundred", "100", "One-hundred")
PLUGIN:AddCPVoice("twohundred", "200", "Two-hundred")
PLUGIN:AddCPVoice("threehundred", "300", "Three-hundred")

-- COMBINE SOLDIER ONLY
Schema.voices.Add("OTA", "PAIN1", "Owwch!", "npc/combine_soldier/pain1.wav")
Schema.voices.Add("OTA", "PAIN2", "Argh!", "npc/combine_soldier/pain2.wav")
Schema.voices.Add("OTA", "PAIN3", "Arh!", "npc/combine_soldier/pain3.wav")

PLUGIN:AddOverwatchVoice("alert1", "ALERT 1", "Alert one!")
PLUGIN:AddOverwatchVoice("nomad", "N", "Nomad")
PLUGIN:AddOverwatchVoice("targetmyradial", "TARGET MY RADIAL", "Target my radial")
PLUGIN:AddOverwatchVoice("targetmyradial", "TARGET RADIAL", "Target my radial")
PLUGIN:AddOverwatchVoice("readyextractors", "READY EXTRACTORS", "Ready extractors!")
PLUGIN:AddOverwatchVoice("extractoraway", "EXTRACTOR AWAY", "Extractor away!")
PLUGIN:AddOverwatchVoice("extractoraway", "EXTRACTOR", "Extractor away!")
PLUGIN:AddOverwatchVoice("readycharges", "READY CHARGES", "Ready charges!")
PLUGIN:AddOverwatchVoice("closing", "CLOSING", "Closing.")
PLUGIN:AddOverwatchVoice("closing2", "CLOSING2", "Closing.")
PLUGIN:AddOverwatchVoice("anticitizenone", "AC1", "Anti-Citizen One")
PLUGIN:AddOverwatchVoice("anticitizenone", "AC ONE", "Anti-Citizen One")
PLUGIN:AddOverwatchVoice("anticitizenone", "ANTICITIZEN 1", "Anti-Citizen One")
PLUGIN:AddOverwatchVoice("anticitizenone", "ANTI-CITIZEN 1", "Anti-Citizen One")
PLUGIN:AddOverwatchVoice("overwatchrequestreserveactivation", "REQUEST RESERVE", "Overwatch, request reserve activation!")
PLUGIN:AddOverwatchVoice("overwatchrequestreserveactivation", "REQUEST RESERVES", "Overwatch, request reserve activation!")
PLUGIN:AddOverwatchVoice("overwatchrequestreserveactivation", "OVERWATCH REQUEST RESERVE ACTIVATION", "Overwatch, request reserve activation!")
PLUGIN:AddOverwatchVoice("overwatchrequestreserveactivation", "OVERWATCH REQUEST RESERVE", "Overwatch, request reserve activation!")
PLUGIN:AddOverwatchVoice("isfinalteamunitbackup", "IS FINAL TEAM UNIT", "is final team unit, request backup!")
PLUGIN:AddOverwatchVoice("isfinalteamunitbackup", "IS FINAL UNIT", "is final team unit, request backup!")


PLUGIN:AddOverwatchVoice("targetblackout", "TARGET BLACKOUT", "Target blackout, sweep and resume.")
PLUGIN:AddOverwatchVoice("lostcontact", "LOST CONTACT", "lost contact.")
PLUGIN:AddOverwatchVoice("motioncheckallradials", "MOTION CHECK ALL RADIALS", "Motion check all radials.")
PLUGIN:AddOverwatchVoice("motioncheckallradials", "CHECK ALL RADIALS", "Motion check all radials.")
PLUGIN:AddOverwatchVoice("motioncheckallradials", "MOTION CHECK", "Motion check all radials.")
PLUGIN:AddOverwatchVoice("stayalertreportsightlines", "STAY ALERT REPORT SIGHTLINES", "Stay alert, report sightlines.")
PLUGIN:AddOverwatchVoice("stayalertreportsightlines", "REPORT SIGHTLINES", "Stay alert, report sightlines.")
PLUGIN:AddOverwatchVoice("fixsightlinesmovein", "FIX SIGHTLINES", "Fix sightlines, move in!")
PLUGIN:AddOverwatchVoice("fixsightlinesmovein", "FIX SIGHTLINE", "Fix sightlines, move in!")
PLUGIN:AddOverwatchVoice("engagedincleanup", "ENGAGED IN CLEANUP", "engaged in cleanup")
PLUGIN:AddOverwatchVoice("engagedincleanup", "IN CLEANUP", "engaged in cleanup")
PLUGIN:AddOverwatchVoice("cleaned", "CLEANED", "Cleaned.")
PLUGIN:AddOverwatchVoice("necrotics", "NECROTICS", "Necrotics.")
PLUGIN:AddOverwatchVoice("necroticsinbound", "NECROTICS INBOUND", "Necrotics inbound.")
PLUGIN:AddOverwatchVoice("weareinaninfestationzone", "INFESTATION ZONE", "we are in an infestation zone.")
PLUGIN:AddOverwatchVoice("weareinaninfestationzone", "WE ARE IN AN INFESTATION ZONE", "we are in an infestation zone.")
PLUGIN:AddOverwatchVoice("wehavenontaggedviromes", "VIROMES", "we have non-tagged viromes.")
PLUGIN:AddOverwatchVoice("swarmoutbreakinsector", "SWARM OUTBREAK IN SECTOR", "swarm outbreak in sector")
PLUGIN:AddOverwatchVoice("swarmoutbreakinsector", "SWARM OUTBREAK", "swarm outbreak in sector")
PLUGIN:AddOverwatchVoice("wehavenontaggedviromes", "VIROMES", "we have non-tagged viromes.")
PLUGIN:AddOverwatchVoice("wehavenontaggedviromes", "NON-TAGGED VIROMES", "we have non-tagged viromes.")
PLUGIN:AddOverwatchVoice("wehavenontaggedviromes", "NONTAGGED VIROMES", "we have non-tagged viromes.")
PLUGIN:AddOverwatchVoice("wehavenontaggedviromes", "WE HAVE NON-TAGGED VIROMES", "we have non-tagged viromes.")
PLUGIN:AddOverwatchVoice("wehavenontaggedviromes", "WE HAVE NONTAGGED VIROMES", "we have non-tagged viromes.")
PLUGIN:AddOverwatchVoice("callcontactparasitics", "CALL CONTACT PARASITE", "Call contact, parasitics.")
PLUGIN:AddOverwatchVoice("callcontactparasitics", "CALL CONTACT PARASITES", "Call contact, parasitics.")
PLUGIN:AddOverwatchVoice("callcontactparasitics", "CALL CONTACT PARASITICS", "Call contact, parasitics.")
PLUGIN:AddOverwatchVoice("callcontactparasitics", "CONTACT PARASITE", "Call contact, parasitics.")
PLUGIN:AddOverwatchVoice("callcontactparasitics", "CONTACT PARASITES", "Call contact, parasitics.")
PLUGIN:AddOverwatchVoice("callcontactparasitics", "CONTACT PARASITIC", "Call contact, parasitics.")
PLUGIN:AddOverwatchVoice("callcontactparasitics", "CONTACT PARASITICS", "Call contact, parasitics.")
PLUGIN:AddOverwatchVoice("wehavefreeparasites", "FREE PARASITE", "We have free parasites.")
PLUGIN:AddOverwatchVoice("wehavefreeparasites", "FREE PARASITES", "We have free parasites.")
PLUGIN:AddOverwatchVoice("wehavefreeparasites", "WE HAVE FREE PARASITE", "We have free parasites.")
PLUGIN:AddOverwatchVoice("wehavefreeparasites", "WE HAVE FREE PARASITES", "We have free parasites.")
PLUGIN:AddOverwatchVoice("contact", "CONTACT", "Contact.")
PLUGIN:AddOverwatchVoice("sterilized", "STERILIZED", "Sterilized.")
PLUGIN:AddOverwatchVoice("contained", "CONTAINED", "Contained.")
PLUGIN:AddOverwatchVoice("containmentproceeding", "CONTAINMENT PROCEEDING", "Containment proceeding.")
PLUGIN:AddOverwatchVoice("overwatchteamisdown", "TEAM IS DOWN", "Overwatch team is down, sector is not controlled.")
PLUGIN:AddOverwatchVoice("overwatchsectoroverrun", "SECTOR OVERRUN", "Overwatch, Sector Overrun repeat Sector Overrun.")
PLUGIN:AddOverwatchVoice("overwatchrequestskyshield", "REQUEST SKYSHIELD", "Overwatch, request Skyshield.")
PLUGIN:AddOverwatchVoice("overwatchrequestwinder", "REQUEST WINDER", "Overwatch, request Winder dispatch.")
PLUGIN:AddOverwatchVoice("hasnegativemovement", "HAS NO MOVEMENT", "Has negative movement.")
PLUGIN:AddOverwatchVoice("hasnegativemovement", "NO MOVEMENT", "Has negative movement.")
PLUGIN:AddOverwatchVoice("hasnegativemovement", "HAS NEGATIVE MOVEMENT", "Has negative movement.")
PLUGIN:AddOverwatchVoice("hasnegativemovement", "NEGATIVE MOVEMENT", "Has negative movement.")
PLUGIN:AddOverwatchVoice("sector", "SECTOR", "Sector")
PLUGIN:AddOverwatchVoice("copy", "COPY", "Copy")
PLUGIN:AddOverwatchVoice("standingby]", "STANDING BY", "Standing by")
PLUGIN:AddOverwatchVoice("copythat", "COPY THAT", "Copy that")
PLUGIN:AddOverwatchVoice("requestmedical", "REQUEST MEDICAL", "Request Medical!")
PLUGIN:AddOverwatchVoice("requeststimdose", "REQUEST STIMDOSE", "Request Stimdose!")
PLUGIN:AddOverwatchVoice("displace", "DISPLACE", "Displace!")
PLUGIN:AddOverwatchVoice("displace2", "DISPLACE2", "Displace!")
PLUGIN:AddOverwatchVoice("alert1", "ALERT ONE", "Alert one!")
PLUGIN:AddOverwatchVoice("bouncerbouncer", "BOUNCER", "Bouncer, bouncer!")
PLUGIN:AddOverwatchVoice("callcontacttarget1", "TARGET ONE", "Call contact suspect Target One.")
PLUGIN:AddOverwatchVoice("contactconfim", "CONTACT CONFIRM", "Contact confirm.")
PLUGIN:AddOverwatchVoice("contactconfirmprosecuting", "CONTACT CONFIRM PROSECUTING", "Contact confirm. Prosecuting!")
PLUGIN:AddOverwatchVoice("cover", "COVER", "Cover.")
PLUGIN:AddOverwatchVoice("coverhurt", "COVER!", "Cover!")
PLUGIN:AddOverwatchVoice("coverme", "COVER ME", "Cover me.")
PLUGIN:AddOverwatchVoice("designatetargetas", "DESIGNATE TARGET AS", "Designate target as... ")
PLUGIN:AddOverwatchVoice("designatetargetas", "TARGET AS", "Designate target as... ")
PLUGIN:AddOverwatchVoice("engaging", "ENGAGING", "Engaging.")
PLUGIN:AddOverwatchVoice("fist", "FIST", "Fist")
PLUGIN:AddOverwatchVoice("flaredown", "FLARE", "Flare down!")
PLUGIN:AddOverwatchVoice("flash", "FLASH", "Flash!")
PLUGIN:AddOverwatchVoice("flatline", "FLATLINE", "Flatline")
PLUGIN:AddOverwatchVoice("flush", "FLUSH", "Flush")
PLUGIN:AddOverwatchVoice("fullactive", "FULL ACTIVE", "Full active.")
PLUGIN:AddOverwatchVoice("executingfullresponse", "FULL RESPONSE", "Executing full response!")
PLUGIN:AddOverwatchVoice("executingfullresponse", "EXECUTING FULL RESPONSE", "Executing full response!")
PLUGIN:AddOverwatchVoice("goactiveintercept", "GO ACTIVE INTERCEPT", "Go active intercept.")
PLUGIN:AddOverwatchVoice("gosharp", "GO SHARP", "Go sharp!")
PLUGIN:AddOverwatchVoice("holdingon10-14duty", "10-14", "Holding on 10-14 duty.", false)
PLUGIN:AddOverwatchVoice("isatcode", "IS AT CODE", "is at code")
PLUGIN:AddOverwatchVoice("isholdingatcode", "IS HOLDING AT CODE", "is holding at code")
PLUGIN:AddOverwatchVoice("noviscon", "NO VISCON", "No Viscon.")
PLUGIN:AddOverwatchVoice("outbreak", "OUTBREAK", "Outbreak!")
PLUGIN:AddOverwatchVoice("reportallpositionsclear", "REPORT ALL CLEAR", "Report all positions clear")
PLUGIN:AddOverwatchVoice("reportallpositionsclear", "REPORT ALL POSITIONS CLEAR", "Report all positions clear")
PLUGIN:AddOverwatchVoice("reportallradialsfree", "REPORT ALL RADIALS FREE", "Report all radials free.")
PLUGIN:AddOverwatchVoice("reportallradialsfree", "REPORT ALL RADIALS", "Report all radials free.")
PLUGIN:AddOverwatchVoice("ripcordripcord", "RIPCORD RIPCORD", "Ripcord! Ripcord")
PLUGIN:AddOverwatchVoice("ripcordripcord", "RIPCORD2", "Ripcord! Ripcord")
PLUGIN:AddOverwatchVoice("sectorissecurenovison", "SECTOR SECURE NO VISCON", "Sector is secure, no Viscon.")
PLUGIN:AddOverwatchVoice("sectorissecurenovison", "SECURE NO VISCON", "Sector is secure, no Viscon.")
PLUGIN:AddOverwatchVoice("sightlineisclear", "SIGHTLINE CLEAR", "Sightline is clear.")
PLUGIN:AddOverwatchVoice("sightlineisclear", "SIGHTLINE IS CLEAR", "Sightline is clear.")
PLUGIN:AddOverwatchVoice("stabilizationteamhassector", "TEAM HAS SECTOR CONTROL", "Stabilization team has sector control.")
PLUGIN:AddOverwatchVoice("stabilizationteamhassector", "TEAM HAS SECTOR", "Stabilization team has sector control.")
PLUGIN:AddOverwatchVoice("stabilizationteamholding", "STABILIZATION TEAM HOLDING IN POSITION", "Stabilization team holding in position.")
PLUGIN:AddOverwatchVoice("stabilizationteamholding", "STABILIZATION TEAM HOLDING", "Stabilization team holding in position.")
PLUGIN:AddOverwatchVoice("stabilizationteamholding", "TEAM HOLDING", "Stabilization team holding in position.")
PLUGIN:AddOverwatchVoice("stabilizationteamholding", "TEAM HOLDING", "Stabilization team is holding in position.")
PLUGIN:AddOverwatchVoice("suppressing", "SUPPRESSING", "Suppressing.")
PLUGIN:AddOverwatchVoice("targetcompromisedmovein", "TARGET COMPROMISED", "Target compromised, move in! Move in!")
PLUGIN:AddOverwatchVoice("targetcontactat", "TARGET AT", "Target contact at")
PLUGIN:AddOverwatchVoice("targetineffective", "TARGET INEFFECTIVE", "Target ineffective.")
PLUGIN:AddOverwatchVoice("targetineffective", "TARGET NO EFFECT", "Target ineffective.")
PLUGIN:AddOverwatchVoice("bodypackholding", "BODYPACK HOLDING", "Bodypack holding.")
PLUGIN:AddOverwatchVoice("targetcontactat", "TARGET CONTACT AT", "Target contact at")
PLUGIN:AddOverwatchVoice("teamdeployedandscanning", "TEAM DEPLOYED", "Team is deployed and scanning.")
PLUGIN:AddOverwatchVoice("teamdeployedandscanning", "TEAM DEPLOYED", "Team is deployed and scanning.")
PLUGIN:AddOverwatchVoice("unitisclosing", "UNIT IS CLOSING", "Unit is closing.")
PLUGIN:AddOverwatchVoice("unitisinbound", "UNIT IS INBOUND", "Unit is inbound.")
PLUGIN:AddOverwatchVoice("unitismovingin", "UNIT IS MOVING IN", "Unit is moving in.")
PLUGIN:AddOverwatchVoice("unitismovingin", "UNIT IS MOVING", "Unit is moving in.")

PLUGIN:AddOverwatchVoice("zero", "0", "Zero")
PLUGIN:AddOverwatchVoice("one", "1", "One")
PLUGIN:AddOverwatchVoice("two", "2", "Two")
PLUGIN:AddOverwatchVoice("three", "3", "Three")
PLUGIN:AddOverwatchVoice("four", "4", "Four")
PLUGIN:AddOverwatchVoice("five", "5", "Five")
PLUGIN:AddOverwatchVoice("six", "6", "Six")
PLUGIN:AddOverwatchVoice("seven", "7", "Seven")
PLUGIN:AddOverwatchVoice("eight", "8", "Eight")
PLUGIN:AddOverwatchVoice("niner", "9", "Nine")
PLUGIN:AddOverwatchVoice("ten", "10", "Ten")
PLUGIN:AddOverwatchVoice("eleven", "11", "Eleven")
PLUGIN:AddOverwatchVoice("twelve", "12", "Twelve")
PLUGIN:AddOverwatchVoice("thirteen", "13", "Thirteen")
PLUGIN:AddOverwatchVoice("fourteen", "14", "Fourteen")
PLUGIN:AddOverwatchVoice("fifteen", "15", "Fifteen")
PLUGIN:AddOverwatchVoice("sixteen", "16", "Sixteen")
PLUGIN:AddOverwatchVoice("seventeen", "17", "Seventeen")
PLUGIN:AddOverwatchVoice("eighteen", "18", "Eighteen")
PLUGIN:AddOverwatchVoice("nineteen", "19", "Nineteen")
PLUGIN:AddOverwatchVoice("twenty", "20", "Twenty")
PLUGIN:AddOverwatchVoice("thirty", "30", "Thirty")
PLUGIN:AddOverwatchVoice("fourty", "40", "Fourty")
PLUGIN:AddOverwatchVoice("fifty", "50", "Fifty")
PLUGIN:AddOverwatchVoice("sixty", "60", "Sixty")
PLUGIN:AddOverwatchVoice("seventy", "70", "Seventy")
PLUGIN:AddOverwatchVoice("eighty", "80", "Eighty")
PLUGIN:AddOverwatchVoice("ninety", "90", "Ninety")
PLUGIN:AddOverwatchVoice("onehundred", "100", "One-hundred")
PLUGIN:AddOverwatchVoice("twohundred", "200", "Two-hundred")
PLUGIN:AddOverwatchVoice("threehundred", "300", "Three-hundred")

PLUGIN:AddOverwatchVoice("meters", "METERS", "Meters")
PLUGIN:AddOverwatchVoice("bearing", "BEARING", "Bearing")
PLUGIN:AddOverwatchVoice("degrees", "DEGREES", "Degrees")

-- METROPOLICE


-- BAD COP

-- ally kill  --------------------------------------------------------------------------------------------------------------------------
PLUGIN:AddBadCopLine("badcop_allypainful1_vocode", "DONT WANNA DO THAT", "Whoop. Don't wanna do that...")
PLUGIN:AddBadCopLine("badcop_allypainful1_vocode", "WHOOP DONT WANNA DO THAT", "Whoop. Don't wanna do that...")
PLUGIN:AddBadCopLine("badcop_allypainful1_vocode", "WHOOPS DONT WANNA DO THAT", "Whoop. Don't wanna do that...")
PLUGIN:AddBadCopLine("badcop_allypainful2_vocode", "THAT LOOKS PAINFUL", "Ooooh.... That looks painful.")
PLUGIN:AddBadCopLine("badcop_allypainful3_vocode", "I BETTER NOT BE NEXT", "Ugh... I better not be next.")
PLUGIN:AddBadCopLine("badcop_allypainful3_vocode", "WALK IT OFF", "Ah, walk it off...")

-- antlion --------------------------------------------------------------------------------------------------------------------------
PLUGIN:AddBadCopLine("badcop_antlionhit1_vocode", "GO POKE SOMEBODY ELSE", "ARGH! Go poke somebody else!")
PLUGIN:AddBadCopLine("badcop_antlionhit2_vocode", "IM NOT A DAMN PIN CUSHION", "ARGH! I'm not a damn pin cushion!")
PLUGIN:AddBadCopLine("badcop_antlionhit3_vocode", "YOU CANT KNOCK ME DOWN", "ARGH! You can't knock me down!")
PLUGIN:AddBadCopLine("badcop_antlionhit4_vocode", "OW LUCKY", "OWWW! You got lucky with that one!")
PLUGIN:AddBadCopLine("badcop_antlionhit4_vocode", "OUCH LUCKY", "OWWW! You got lucky with that one!")
PLUGIN:AddBadCopLine("badcop_antlionhit4_vocode", "OW YOU GOT LUCKY", "OWWW! You got lucky with that one!")
PLUGIN:AddBadCopLine("badcop_antlionhit4_vocode", "OUCH YOU GOT LUCKY", "OWWW! You got lucky with that one!")
PLUGIN:AddBadCopLine("badcop_antlionhit5_vocode", "RUDE TO POKE", "ARGH! It's rude to poke!")
PLUGIN:AddBadCopLine("badcop_antlionhit6_vocode", "WANT A BULLET TO THE HEAD?", "Ahh! What's that?! You want a bullet to the head!?")
PLUGIN:AddBadCopLine("badcop_antlionhit7_vocode", "I GAVE YOU THAT ONE FOR FREE", "Argh! I gave you that one for free!")
PLUGIN:AddBadCopLine("badcop_antlionhit8_vocode", "THAT ONE TINGLED", "Argh! That one kind of tingled!")

-- apc crash  --------------------------------------------------------------------------------------------------------------------------

PLUGIN:AddBadCopLine("badcop_apc_crash1_vocode", "WOOPS", "Woops.")
PLUGIN:AddBadCopLine("badcop_apc_crash2_vocode", "I MEANT TO DO THAT", "Oooof. I meant to do that.")
PLUGIN:AddBadCopLine("badcop_apc_crash3_vocode", "DRIVING ON ICE", "Driving on ice is not as fun as I thought it would be.")
PLUGIN:AddBadCopLine("badcop_apc_crash4_vocode", "HOPE OUT OF PAY CHECK", "Ooh. I hope they don't take that out of my paycheck")
PLUGIN:AddBadCopLine("badcop_apc_crash5_vocode", "WILL BUFF OUT", "Urgh. I'm sure that will buff out.")

PLUGIN:AddBadCopLine("badcop_apc_damage1_vocode", "HOLD IT TOGETHER BABY", "Hold it together, baby!")
PLUGIN:AddBadCopLine("badcop_apc_damage2_vocode", "SUDDENLY EXPLODE", "This thing better not suddenly explode on me")
PLUGIN:AddBadCopLine("badcop_apc_damage2_vocode", "THIS THING BETTER NOT SUDDENLY EXPLODE", "This thing better not suddenly explode on me")
PLUGIN:AddBadCopLine("badcop_apc_damage3_vocode", "OW IM NOT INVINCIBLE IN THIS THING", "Oww! Shit. Look's like i'm not invincible on this thing.")
PLUGIN:AddBadCopLine("badcop_apc_damage4_vocode", "BETTER HAVE INSURANCE", "Argh. You better have insurance...")
PLUGIN:AddBadCopLine("badcop_apc_damage5_vocode", "HAH NOW YOU HAVE MY ATTENTION", "Now you have my attention...")

-- APC FLIP
PLUGIN:AddBadCopLine("badcop_apc_flipped_vocode", "IM NOT THE DRIFT KING", "Aaaaahhh... Shit.... Guess I'm not the drift king.")

-- APC KILL
PLUGIN:AddBadCopLine("badcop_apc_kill_gun1_vocode", "FINALLY GET TO USE", "It's so awesome I finally get to use this thing")
PLUGIN:AddBadCopLine("badcop_apc_kill_gun2_vocode", "DID YOU THINK YOU HAD A CHANCE", "AHAHAHAHAHAHA. DID YOU HONESTLY THINK YOU HAD A CHANCE?")
PLUGIN:AddBadCopLine("badcop_apc_kill_gun3_vocode", "GRATEFUL FOR TARGET PRACTICE", "I'm really grateful for the target practice.")
PLUGIN:AddBadCopLine("badcop_apc_kill_gun4_vocode", "MY GUN IS BIGGER", "MY GUN IS BIGGER THAN YOURS.")
PLUGIN:AddBadCopLine("badcop_apc_kill_gun5_vocode", "YOU THINK YOU STOOD A CHANCE", "You think you stood a chance against this?")

-- TODO: Separate later

PLUGIN:AddBadCopLine("badcop_apc_kill_rocket1_vocode", "KABOOM", "Ka-boom.")
PLUGIN:AddBadCopLine("badcop_apc_kill_rocket2_vocode", "BURY IN SOUP CAN", "I'll be burying what's left of you in a SOUP CAN.")
PLUGIN:AddBadCopLine("badcop_apc_kill_rocket3_vocode", "GOOD LUCK ID BODY", "Good luck identifying THAT body.")
PLUGIN:AddBadCopLine("badcop_apc_kill_rocket4_vocode", "WISH I HAD IN CITY 10", "I wish I had some of these back in City 10.")
PLUGIN:AddBadCopLine("badcop_apc_kill_rocket5_vocode", "SAY HELLO TO MY LITTLE FRIEND", "SAY HELLO TO MY LITTLE FRIEND")

PLUGIN:AddBadCopLine("badcop_apc_request_vocode", "OVERWATCH MY VEHICLE IS FUCKED", "Overwach... My... uhm... Vehicular Transporation is... inoperable... Requesting replacement...            Please.... Over.")

PLUGIN:AddBadCopLine("badcop_apc_roadkill1_vocode", "LIKE BUGS ON A WINDSHIELD", "Like bugs on a windshield.")
PLUGIN:AddBadCopLine("badcop_apc_roadkill2_vocode", "ANYBODY ELSE SEE THAT", "Hah. Did anybody else see that?")
PLUGIN:AddBadCopLine("badcop_apc_roadkill3_vocode", "YOU SHOULD HAVE STAYED INDOORS", "You should have stayed indoors.")
PLUGIN:AddBadCopLine("badcop_apc_roadkill4_vocode", "WHOS NEXT", "Hah. Who's next..?")
PLUGIN:AddBadCopLine("badcop_apc_roadkill5_vocode", "DIDNT DO THIS BACK IN THE DAY", "Hah. Didn't get to do this back in the day.")
    
PLUGIN:AddBadCopLine("badcop_blunthit1_vocode", "THROWING SHIT", "Argh! Throwing shit..?- Seriously??")
PLUGIN:AddBadCopLine("badcop_blunthit2_vocode", "FOR FUCKS SAKE", "Argh. For fucks sake.")
PLUGIN:AddBadCopLine("badcop_blunthit3_vocode", "CUT THAT SHIT OUT", "Argh. Cut that shit out.")
PLUGIN:AddBadCopLine("badcop_blunthit4_vocode", "SWALLOW MY GUM", "Ow. You almost made me swallow my gum. (If I had any)")
PLUGIN:AddBadCopLine("badcop_blunthit5_vocode", "IF I HAD TIME TEAR YOU APART", "Argh!!. If I had the time i'd TEAR YOU APART WITH MY BARE HANDS")
PLUGIN:AddBadCopLine("badcop_blunthit6_vocode", "ARGH NOW IM ANGRY", "Argh!! Oooooh... Now i'm angry.")
-- I have no fucking idea what he says on this line
-- !PLUGIN:AddBadCopLine("badcop_blunthit7_vocode", "", "")
PLUGIN:AddBadCopLine("badcop_blunthit8_vocode", "HIT THE GUT", "Ough... Oh I think that one hit me in the gut..")


PLUGIN:AddBadCopLine("badcop_burnt1_vocode", "OH HOT", "Oh hot hot hot! hothothothot!")
PLUGIN:AddBadCopLine("badcop_burnt2_vocode", "NOT FIRE RETARDANT", "Argh! Jeeze! This suit is not fire retardant!")
PLUGIN:AddBadCopLine("badcop_burnt3_vocode", "THAT BURNS", "Argh! ARgh!! ARGHH JESUS THAT BURNS")
PLUGIN:AddBadCopLine("badcop_burnt4_vocode", "THATS GONNA LEAVE A MARK", "Argh! ARgh!! Ah, shit! That's gonna leave a mark!")
PLUGIN:AddBadCopLine("badcop_burnt5_vocode", "OH YEAH FIRE HURTS", "Ouuw! Argh! Ow! Oh yeah, fire still hurts.")

PLUGIN:AddDispatchVoice("attentionyouhavebeenchargedwith", "CHARGED WITH", "Attention. You have been charged with: ")
PLUGIN:AddDispatchVoice("alarms62", "62", "62-Alarms.")
PLUGIN:AddDispatchVoice("threattoproperty51b", "51B", "51B-Threat to property.")
PLUGIN:AddDispatchVoice("resistingpacification148", "148", "148-Resisting arrest.")
PLUGIN:AddDispatchVoice("riot404", "404", "404-Riot.")
PLUGIN:AddDispatchVoice("unlawfulentry603", "603", "603-Unlawful entry.")
PLUGIN:AddDispatchVoice("assault243", "243", "243-Assault on Protection Team.")
PLUGIN:AddDispatchVoice("attemptedcrime27", "27", "27-Attempted Crime.")
PLUGIN:AddDispatchVoice("fugitive17f", "17F", "17F-Fugitive Detachment.")
PLUGIN:AddDispatchVoice("illegalcarrying95", "95", "95-Illegal Carrying.")
PLUGIN:AddDispatchVoice("illegalinoperation63s", "63", "63-Illegal in operation.")
PLUGIN:AddDispatchVoice("weapon94", "94", "94-Weapon.")
PLUGIN:AddDispatchVoice("posession69", "69", "69-Posession of resources.")
PLUGIN:AddDispatchVoice("incitingpopucide", "DIVISIVE", "Divisive sociocidal counter-obeyance.")
PLUGIN:AddDispatchVoice("publicnoncompliance507", "507", "507-Public non compliance.")
PLUGIN:AddDispatchVoice("recklessoperation99", "99", "99-Reckless operation.") -- 
PLUGIN:AddDispatchVoice("criminaltrespass63", "63", "63-Criminal tresspass.")
PLUGIN:AddDispatchVoice("disengaged647e", "647E", "647E-Disengaged from workforce.")
PLUGIN:AddDispatchVoice("disturbancemental10-103m", "10-103M", "10-103M-Disturbance by mentally unfit.")
PLUGIN:AddDispatchVoice("disturbingunity415", "415", "415-Civic Disunity.")
PLUGIN:AddDispatchVoice("nonsanctionedarson51", "51", "51-Non sanctioned arson.")
PLUGIN:AddDispatchVoice("failuretocomply", "FAILURE TO COMPLY", "Failure to comply with the Civil Will.")
PLUGIN:AddDispatchVoice("promotingcommunalunrest", "PROMOTING UNREST", "Promoting communal unrest.")
PLUGIN:AddDispatchVoice("failuretocomply", "FAILURE TO COMPLY WITH THE CIVIL WILL", "Failure to comply with the civil will.")
PLUGIN:AddDispatchVoice("capitalmalcompliance", "CAPITAL MALCOMPLIANCE", "Capital Malcompliance.")
PLUGIN:AddDispatchVoice("destrutionofcpt", "DESTRUCTION OF CPT", "Destruction of corporal Social Protection units.")
PLUGIN:AddDispatchVoice("destrutionofcpt", "DESTRUCTION OF CSPT", "Destruction of corporal Social Protection units.")
PLUGIN:AddDispatchVoice("disassociationfromcivic", "DISASSOCIATION FROM POPULACE", "Disassociation From Civic Populace.")
PLUGIN:AddDispatchVoice("level5anticivilactivity", "LEVEL 5 ANTI-CIVIL ACTIVITY", "Level FIVE anti-civil activity.")
PLUGIN:AddDispatchVoice("level5anticivilactivity", "LEVEL 5 ACTIVITY", "Level FIVE anti-civil activity.")
PLUGIN:AddDispatchVoice("level5anticivilactivity", "LEVEL 5", "Level FIVE anti-civil activity.")
PLUGIN:AddDispatchVoice("sociocide", "SOCIOCIDE", "Sociocide.")
PLUGIN:AddDispatchVoice("violationofcivictrust", "VIOLATION OF CIVIC TRUST", "Violation of civic trust.")
PLUGIN:AddDispatchVoice("violationofcivictrust", "CIVIC TRUST", "Violation of civic trust.")
PLUGIN:AddDispatchVoice("youarejudgedguilty", "GUILTY", "You are judged guilty by Civil Protection teams!")

PLUGIN:AddDispatchVoice("fcitadel_confiscating", "CONFISCATION FIELD", "Security Alert: Unregistered weapons detected. Confiscation field, engaged.", true)
PLUGIN:AddDispatchVoice("fcitadel_confiscationfailure", "CONFISCATION FIELD FAILURE", "Warning: Counter-resonant singularity device detected. Confiscation field failure.", true)
PLUGIN:AddDispatchVoice("fcitadel_deploy", "SINGULARITY DEVICE", "Security Alert: Illegal Counter-Resonant Singularity Device detected. DEPLOY, DIAGNOSE, DISSECT.", true)
PLUGIN:AddDispatchVoice("fcitadel_transportsequence", "TRANSPORT SINGULARITY", "Attention: Transport singularity interlock sequence engaged.", true)
PLUGIN:AddDispatchVoice("fprison_interfacebypass", "VIRAL INTERFACE", "Warning: Malignant viral interface bypass detected. Polyphasic core reprogramming detected. Sterrilizers and containment fields may be compromised.", true)
PLUGIN:AddDispatchVoice("fcitadel_2minutestosingularity", "2MIN TO SINGULARITY", "Warning: Two minutes to singularity.", true)
PLUGIN:AddDispatchVoice("fcitadel_1minutetosingularity", "1MIN TO SINGULARITY", "Warning: One minute to singularity.", true)
PLUGIN:AddDispatchVoice("fcitadel_45sectosingularity", "45S TO SINGULARITY", "Priority Warning: 45 Seconds to singularity.", true)
PLUGIN:AddDispatchVoice("fcitadel_30sectosingularity", "30S TO SINGULARITY", "Priority Warning: 30 Seconds to singularity.", true)
PLUGIN:AddDispatchVoice("fcitadel_15sectosingularity", "15S TO SINGULARITY", "Priority Warning: 15 Seconds to singularity.", true)
PLUGIN:AddDispatchVoice("fcitadel_10sectosingularity", "10S TO SINGULARITY", "Priority Warning: 10 Seconds to singularity.", true)


PLUGIN:AddDispatchVoice("one", "1", "One.")
PLUGIN:AddDispatchVoice("two", "2", "Two.")
PLUGIN:AddDispatchVoice("three", "3", "Three.")
PLUGIN:AddDispatchVoice("four", "4", "Four.")
PLUGIN:AddDispatchVoice("five", "5", "Five.")
PLUGIN:AddDispatchVoice("six", "6", "Six.")
PLUGIN:AddDispatchVoice("seven", "7", "Seven.")
PLUGIN:AddDispatchVoice("eight", "8", "Eight.")
PLUGIN:AddDispatchVoice("nine", "9", "Nine.")

PLUGIN:AddDispatchVoice("engagingteamisnoncohesive", "ENGAGING PT IS NON COHESIVE", "Engaging Protection Team is non-cohesive.")
PLUGIN:AddDispatchVoice("404zone", "404 ZONE", "404 Zone")
PLUGIN:AddDispatchVoice("accomplicesoperating", "ACCOMPLICES", "Protection Team, Be Advised: Accomplices operating in area.")
PLUGIN:AddDispatchVoice("administer", "ADMINISTER", "Administer.")
PLUGIN:AddDispatchVoice("airwatchcopiesnoactivity", "AIRWATCH NO ACTIVITY", "Airwatch copies no activity in location.")
PLUGIN:AddDispatchVoice("airwatchcopiesnoactivity", "AIRWATCH COPIES NO ACTIVITY", "Airwatch copies no activity in location.")
PLUGIN:AddDispatchVoice("airwatchreportspossiblemiscount", "AIRWATCH REPORTS POSSIBLE MISCOUNT", "Airwatch reports possible miscount.")
PLUGIN:AddDispatchVoice("airwatchreportspossiblemiscount", "POSSIBLE MISCOUNT", "Airwatch reports possible miscount.")
PLUGIN:AddDispatchVoice("allteamsrespondcode3", "CODE 3", "All teams, respond Code 3.")
PLUGIN:AddDispatchVoice("allteamsrespondcode3", "RESPOND CODE 3", "All teams, respond Code 3.")
PLUGIN:AddDispatchVoice("allunitsapplyforwardpressure", "APPLY PRESSURE", "All units, apply forward pressure.")
PLUGIN:AddDispatchVoice("allunitsat", "ALL UNITS AT", "All units at")
PLUGIN:AddDispatchVoice("allunitsbeginwhitnesssterilization", "WHITNESS STERILIZATION", "All units begin whitness sterilization.")
PLUGIN:AddDispatchVoice("allunitsbeginwhitnesssterilization", "WHITNESS STERILIZATION", "All units begin whitness sterilization.")
PLUGIN:AddDispatchVoice("allunitsbolfor243suspect", "BOL 243", "All units, BOL for 243 suspect.")
PLUGIN:AddDispatchVoice("allunitsdeliverterminalverdict", "TERMINAL VERDICT", "All units, deliver Terminal Verdict immediately.")
PLUGIN:AddDispatchVoice("allunitsreturntocode12", "CODE 12", "All units, return to Code 12.")
PLUGIN:AddDispatchVoice("allunitsverdictcodeis", "VERDICT CODE IS", "All units, verdict code is...")
PLUGIN:AddDispatchVoice("allunitsverdictcodeis", "VERDICT CODE ON SUSPECT", "All units, verdict code on suspect.")
PLUGIN:AddDispatchVoice("amputate", "AMPUTATE", "Amputate.")
PLUGIN:AddDispatchVoice("anticitizen", "ANTICITIZEN", "Anti-citizen.")
PLUGIN:AddDispatchVoice("anticitizen", "ANTI-CITIZEN", "Anti-citizen.")
PLUGIN:AddDispatchVoice("antifatigueration3mg", "ANTI-FATIGUE", "Anti-fatigue ration is now: 3 miligrams.")
PLUGIN:AddDispatchVoice("apply", "APPLY", "Apply.")
PLUGIN:AddDispatchVoice("attention", "ATTENTION", "Attention: ")
PLUGIN:AddDispatchVoice("beginscanning10av", "10-0", "10-0. Begin scanning.")
PLUGIN:AddDispatchVoice("block", "BLOCK", "Block.")
PLUGIN:AddDispatchVoice("canalblock", "CANAL BLOCK", "Canal Block.")
PLUGIN:AddDispatchVoice("cauterize", "CAUTERIZE", "Cauterize.")
PLUGIN:AddDispatchVoice("citizen", "CITIZEN", "Citizen.")
PLUGIN:AddDispatchVoice("completesentencingatwill", "SENTENCING AT WILL", "All Protection Team units, complete sentencing at will.")
PLUGIN:AddDispatchVoice("condemnedzone", "CONDEMNED ZONE", "Condemned Zone.")
PLUGIN:AddDispatchVoice("confirmupialert", "CONFIRM UPI", "Team, confirm UPI alert.")
PLUGIN:AddDispatchVoice("defender", "DEFENDER", "Defender.")
PLUGIN:AddDispatchVoice("deservicedarea", "RESTRICTED BLOCK", "Restricted Block.")
PLUGIN:AddDispatchVoice("document", "DOCUMENT", "Document.")
PLUGIN:AddDispatchVoice("examine", "EXAMINE", "Examine.")
PLUGIN:AddDispatchVoice("externaljurisdiction", "EXTERNAL JURISDICTION", "External Jurisdiction.")
PLUGIN:AddDispatchVoice("failuretotreatoutbreak", "FAILURE TO TREAT OUTBREAK", "Stabilization Team: failure to treat identified local outbreak will force team recall and recycle")
PLUGIN:AddDispatchVoice("finalverdictadministered", "FINAL VERDICT", "Final Verdict administered.")
PLUGIN:AddDispatchVoice("fmil_region_073", "SKYSHIELD", "Sky Shield.")
PLUGIN:AddDispatchVoice("freeman", "FREEMAN", "Freeman.")
PLUGIN:AddDispatchVoice("halfrankpoints", "50 PERCENT RANK POINTS", "50 percent rank points")
PLUGIN:AddDispatchVoice("halfreproductioncredits", "50 PERCENT REPRODUCTION POINTS", "50 percent reproduction credits")
PLUGIN:AddDispatchVoice("hero", "HERO", "Hero.")
PLUGIN:AddDispatchVoice("highpriorityregion", "HIGH PRIORITY REGION", "High priority region.")
PLUGIN:AddDispatchVoice("immediateamputation", "IMMEDIATE AMPUTATION", "Immediate amputation.")
PLUGIN:AddDispatchVoice("industrialzone", "INDUSTRIAL", "Industrial Zone.")
PLUGIN:AddDispatchVoice("industrialzone", "INDUSTRIAL ZONE", "Industrial Zone.")
PLUGIN:AddDispatchVoice("infection", "INFECTION", "Infection.")
PLUGIN:AddDispatchVoice("inject", "INJECT", "Inject.")
PLUGIN:AddDispatchVoice("innoculate", "INNOCULATE", "Innoculate.")
PLUGIN:AddDispatchVoice("innoculate", "INOCULATE", "Innoculate.")
PLUGIN:AddDispatchVoice("inprogress", "IN PROGRESS", "In progress.")
PLUGIN:AddDispatchVoice("interlock", "INTERLOCK", "Interlock.")
PLUGIN:AddDispatchVoice("investigate", "INVESTIGATE", "Investigate.")
PLUGIN:AddDispatchVoice("investigateandreport", "INVESTIGATE AND REPORT", "Investigate and report.")
PLUGIN:AddDispatchVoice("isnow", "IS NOW", "is now")
PLUGIN:AddDispatchVoice("isolate", "ISOLATE", "Isolate")
PLUGIN:AddDispatchVoice("jury", "JURY", "Jury")
PLUGIN:AddDispatchVoice("king", "KING", "King")
PLUGIN:AddDispatchVoice("leadersreportratios", "REPORT DEAD UNIT", "Attention Stabilization Team leader. Report de-serviced unit to sterilized body count ratio for reinforcement, reward, or removal processing.")
PLUGIN:AddDispatchVoice("line", "LINE", "Line")
PLUGIN:AddDispatchVoice("lock", "LOCK", "Lock")
PLUGIN:AddDispatchVoice("lockdownlocationsacrificecode", "LOCKDOWN SACRIFICE CODE", "Protection Team: lock down your location: sacrifice code.")
PLUGIN:AddDispatchVoice("lostbiosignalforunit", "LOST BIOSIGNAL", "Lost bio signal for Protection Team unit")
PLUGIN:AddDispatchVoice("noncitizen", "NON CITIZEN", "Non-citizen")
PLUGIN:AddDispatchVoice("noncitizen", "NONCITIZEN", "Non-citizen")
PLUGIN:AddDispatchVoice("noncitizen", "NON-CITIZEN", "Non-citizen")
PLUGIN:AddDispatchVoice("nonpatrolregion", "NON PATROL REGION", "Non-patrol region")
PLUGIN:AddDispatchVoice("nonpatrolregion", "NONPATROL REGION", "Non-patrol region")
PLUGIN:AddDispatchVoice("nonpatrolregion", "NON-PATROL REGION", "Non-patrol region")
PLUGIN:AddDispatchVoice("officerat", "OFFICER", "Officer")
PLUGIN:AddDispatchVoice("politistablizationmarginal", "MARGINAL", "Notice: Protection Teams: Civic politistabilization index is marginal.")
PLUGIN:AddDispatchVoice("prematuremissiontermination", "PREMATURE TERMINATION", "Premature mission termination will result in")
PLUGIN:AddDispatchVoice("prepareforfinalsentencing", "PREPARE FOR FINAL SENTENCING", "Prepare for final sentencing")
PLUGIN:AddDispatchVoice("prepareforfinalsentencing", "FINAL SENTENCING", "Prepare for final sentencing")
PLUGIN:AddDispatchVoice("preparetoinnoculate", "PREPARE TO INNOCULATE", "All local Protection Team units: prepare to inoculate")
PLUGIN:AddDispatchVoice("preparetoinnoculate", "PREPARE TO INOCULATE", "All local Protection Team units: prepare to inoculate")
PLUGIN:AddDispatchVoice("preparetoreceiveverdict", "PREPARE TO RECEIVE VERDICT", "Prepare to receive verdict.")
PLUGIN:AddDispatchVoice("preparevisualdownload", "VISUAL DOWNLOAD", "Attention: prepare visual download of anti-citizen one.")
PLUGIN:AddDispatchVoice("preserve", "PRESERVE", "Preserve")
PLUGIN:AddDispatchVoice("pressure", "PRESSURE", "Pressure")
PLUGIN:AddDispatchVoice("productionblock", "PRODUCTION BLOCK", "Production block")
PLUGIN:AddDispatchVoice("prosecute", "Prosecute", "Prosecute")
PLUGIN:AddDispatchVoice("quick", "QUICK", "Quick")
PLUGIN:AddDispatchVoice("recalibratesocioscan", "SOCIOSCAN", "Team: recalibrate socioscan")
PLUGIN:AddDispatchVoice("recalibratesocioscan", "SOCIO SCAN", "Team: recalibrate socioscan")
PLUGIN:AddDispatchVoice("recievingconflictingdata", "CONFLICTING DATA", "We are receiving conflicting data.")
PLUGIN:AddDispatchVoice("reinforcementteamscode3", "REINFORCEMENTS CODE 3", "Reinforcement Teams: Code 3")
PLUGIN:AddDispatchVoice("remainingunitscontain", "REMAINING UNITS CONTAIN", "Remaining units contain")
PLUGIN:AddDispatchVoice("reminder100credits", "100 CREDITS", "Rank leader: reminder: 100 sterilized credits qualifies non-mechanical reproduction simulation")
PLUGIN:AddDispatchVoice("remindermemoryreplacement", "MEMORY REPLACEMENT", "Reminder: Memory replacement is the first step toward rank privileges.")
PLUGIN:AddDispatchVoice("reporton", "REPORT ON", "Local Protection Team units report on")
PLUGIN:AddDispatchVoice("reportplease", "REPORT PLEASE", "Report please")
PLUGIN:AddDispatchVoice("repurposedarea", "REPURPOSED AREA", "Repurposed area")
PLUGIN:AddDispatchVoice("residentialblock", "RESIDENTIAL", "Residential Block")
PLUGIN:AddDispatchVoice("residentialblock", "RESIDENTIAL BLOCK", "Residential Block")
PLUGIN:AddDispatchVoice("respond", "RESPOND", "Respond")
PLUGIN:AddDispatchVoice("restrict", "RESTRICT", "Restrict")
PLUGIN:AddDispatchVoice("restrictedblock", "RESTRICTED BLOCK", "Restricted Block")
PLUGIN:AddDispatchVoice("restrictedincursioninprogress", "RESTRICTED INCURSION", "Restricted incursion in progress.")
PLUGIN:AddDispatchVoice("rewardnotice", "REWARD NOTICE", "Reward notice: Protection Team member: your family cohesion is preserved.")
PLUGIN:AddDispatchVoice("roller", "ROLLER", "Roller")
PLUGIN:AddDispatchVoice("search", "SEARCH", "Search")
PLUGIN:AddDispatchVoice("sector", "SECTOR", "Sector")
PLUGIN:AddDispatchVoice("serve", "SERVE", "Serve")
PLUGIN:AddDispatchVoice("socialfractureinprogress", "SOCIAL FRACTURE", "Social fracture in progress. Respond.")
PLUGIN:AddDispatchVoice("sociocide", "SOCIOCIDE", "Sociocide")
PLUGIN:AddDispatchVoice("sociostabilizationrestored", "SOCIOSTABILIZATION RESTORED", "Sociostabilization restored.")
PLUGIN:AddDispatchVoice("stabilizationjurisdiction", "STABILIZATION JURISDICTION", "Stabilization jurisdiction.")
PLUGIN:AddDispatchVoice("stationblock", "STATION BLOCK", "Station block")
PLUGIN:AddDispatchVoice("statuson243suspect", "REPORT STATUS ON 243", "All units report status on 243 suspect.")
PLUGIN:AddDispatchVoice("sterilize", "STERILIZE", "Sterilize.")
PLUGIN:AddDispatchVoice("stick", "STICK", "Stick")
PLUGIN:AddDispatchVoice("stormsystem", "STORM SYSTEM", "Storm system")
PLUGIN:AddDispatchVoice("subject", "SUBJECT", "Subject")
PLUGIN:AddDispatchVoice("suspectisnow187", "SUSPECT IS NOW 187", "Suspect is now 1-8-7")
PLUGIN:AddDispatchVoice("suspectmalignantverdictcodeis", "SUSPECT IS JUDGED MALIGNANT", "Suspect is judged malignant. Verdict code is")
PLUGIN:AddDispatchVoice("suspend", "SUSPEND", "Suspend")
PLUGIN:AddDispatchVoice("suspendnegotiations", "SUSPEND NEGOTIATIONS", "Suspend negotiations")
PLUGIN:AddDispatchVoice("switchcomtotac3", "TAC3", "All units switch com to tac 3")
PLUGIN:AddDispatchVoice("switchtotac5reporttocp", "TAC5 AND CP", "All units switch com to tac 5 and report in to command point.")
PLUGIN:AddDispatchVoice("tap", "TAP", "Tap")
PLUGIN:AddDispatchVoice("teamsreportstatus", "REPORT STATUS", "Local Civil Protection Teams report status.")
PLUGIN:AddDispatchVoice("terminalprosecution", "TERMINAL PROSECUTION", "Terminal prosecution")
PLUGIN:AddDispatchVoice("terminalrestrictionzone", "TERMINAL RESTRICTION ZONE", "Terminal restriction zone")
PLUGIN:AddDispatchVoice("transitblock", "TRANSIT BLOCK", "Transit block") -- 
PLUGIN:AddDispatchVoice("union", "UNION", "Union")
PLUGIN:AddDispatchVoice("unitdeserviced", "UNIT DESERVICED", "Unit deserviced")
PLUGIN:AddDispatchVoice("unitdownat", "UNIT DOWN AT", "Unit down at")
PLUGIN:AddDispatchVoice("vice", "VICE", "Vice")
PLUGIN:AddDispatchVoice("victor", "VICTOR", "Victor")
PLUGIN:AddDispatchVoice("workforceintake", "WORKFORCE INTAKE HUB", "Workforce intake hub.")
PLUGIN:AddDispatchVoice("xray", "X-RAY", "X-Ray")
PLUGIN:AddDispatchVoice("xray", "XRAY", "X-Ray")
PLUGIN:AddDispatchVoice("yellow", "YELLOW", "Yellow")
PLUGIN:AddDispatchVoice("youarechargedwithterminal", "148 243 245", "You are charged with terminal violations 148, 243, 245")
PLUGIN:AddDispatchVoice("zone", "ZONE", "Zone")


