function PLUGIN:AddVortVoice(clip, key, value)
    local vtype = "Vort"
    Schema.voices.Add(vtype, key, value, "vo/npc/vortigaunt/" .. clip .. ".wav")
end

Schema.voices.AddClass("Vort", function(client)
    return (client:Team() == FACTION_VORT)
end)

PLUGIN:AddVortVoice("acceptcharge", "ACCEPT CHARGE", "Accept the charge.")
PLUGIN:AddVortVoice("acceptenergy", "ACCEPT ENERGY", "Accept energy.")
PLUGIN:AddVortVoice("accompany", "ACCOMPANY", "Gladly we accompany.")
PLUGIN:AddVortVoice("affirmed", "AFFIRMED", "Affirmed.")
PLUGIN:AddVortVoice("alldear", "ALL DEAR", "We have lost all dear to us.")
PLUGIN:AddVortVoice("allfornow", "ALL FOR NOW", "That is all for now.")
PLUGIN:AddVortVoice("allinoneinall", "ALL IN ONE", "All in one and one in all.")
PLUGIN:AddVortVoice("allowme", "ALLOW ME", "Allow me")
PLUGIN:AddVortVoice("allowrecharge", "ALLOW RECHARGE", "Allow us to recharge your cells.")
PLUGIN:AddVortVoice("allwecanspare", "ALL WE CAN SPARE", "That is all we can spare.")
PLUGIN:AddVortVoice("allwehave", "ALL WE HAVE", "All we have is yours.")
PLUGIN:AddVortVoice("assent", "ASSENT", "Assent")
PLUGIN:AddVortVoice("asyouwish", "AS YOU WISH", "As you wish")
PLUGIN:AddVortVoice("beofservice", "BE OF SERVICE", "Can we be of service?")
PLUGIN:AddVortVoice("bodyyours", "BODY IS YOURS", "This body is yours to command.")
PLUGIN:AddVortVoice("calm", "CALM YOURSELF", "Calm yourself.")
PLUGIN:AddVortVoice("canconvince", "CONVINCE", "Can we not convince you otherwise?")
PLUGIN:AddVortVoice("cannotfire", "FIRE WITHOUT HARM FREEMAN", "We cannot fire without harm to the Freeman.")
PLUGIN:AddVortVoice("cannotfire", "FIRE WITHOUT HARM FREE MAN", "We cannot fire without harm to the Free Man.")
PLUGIN:AddVortVoice("caution", "CAUTION", "Caution")
PLUGIN:AddVortVoice("cautionfm", "CAUTION FREEMAN", "Caution, Freeman!")
PLUGIN:AddVortVoice("cautionfm", "CAUTION FREE MAN", "Caution, Free Man!")
PLUGIN:AddVortVoice("certainly", "certainly", "Certainly")
PLUGIN:AddVortVoice("corporeal", "corporeal", "We never dreamed to meet you in corporeal form.")
PLUGIN:AddVortVoice("dedicate", "WE DEDICATE", "We dedicate ourselves to your purpose.")
PLUGIN:AddVortVoice("done", "done", "Done")
PLUGIN:AddVortVoice("dreamed", "DREAMED", "We have dreamed of this moment.")
PLUGIN:AddVortVoice("empowerus", "empower us", "Empower us!")
PLUGIN:AddVortVoice("energyempower", "ENERGY EMPOWER", "Its energy empowers us.")
PLUGIN:AddVortVoice("fearfailed", "WE HAVE FAILED YOU", "We fear we have failed you.")
PLUGIN:AddVortVoice("forfreedom", "FOR FREEDOM", "For Freedom!")
PLUGIN:AddVortVoice("forward", "forward", "Forward!")
PLUGIN:AddVortVoice("freeman", "freeman", "Freeman")
PLUGIN:AddVortVoice("giveover", "give over", "Give over your essence.")
PLUGIN:AddVortVoice("gladly", "gladly", "Gladly")
PLUGIN:AddVortVoice("gloriousend", "GLORIOUS END", "To our glorious end.")
PLUGIN:AddVortVoice("halt", "halt", "Halt!")
PLUGIN:AddVortVoice("here", "here", "Here")
PLUGIN:AddVortVoice("herewestay", "here we stay", "Here we stay")
PLUGIN:AddVortVoice("hold", "hold", "Hold")
PLUGIN:AddVortVoice("holdorcantcharge", "hold cant charge", "Hold still or we cannot charge you.")
PLUGIN:AddVortVoice("holdstill", "hold still", "Hold still")

