ITEM.name = "Satchel"
ITEM.description = "A satchel used to hold items."
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.category = "Storage"
ITEM.width = 2
ITEM.height = 1
ITEM.invWidth = 3
ITEM.invHeight = 2
ITEM.isBag = true